const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_LIMIT: 'GET_POSTS_LIMIT',
    GET_POSTS_LIMIT_PRICE: 'GET_POSTS_LIMIT_PRICE',
    GET_POSTS_LIMIT_ACREAGE: 'GET_POSTS_LIMIT_ACREAGE',
    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_CURRENT: 'GET_CURRENT'
}

export default actionTypes;